services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      - devhabit.aspire-dashboard

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      # WARNING: Anonymous access enabled for local dev only. DO NOT use in production.
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
  