@DevHabit.Api_HostAddress = http://localhost:5123

POST {{DevHabit.Api_HostAddress}}/auth/register
Content-Type: application/json
Accept: application/vnd.teqniqly.devhabit+json

{
  "email": "foo9@bar.com",
  "password": "Hello123!",
  "confirmPassword": "Hello123!",
  "name": "Bubba Gump9"
}
###
