@DevHabit.Api_HostAddress = http://localhost:5123

GET {{DevHabit.Api_HostAddress}}/habits

###

GET {{DevHabit.Api_HostAddress}}/habits/h_0199e8ce-4522-7d72-9fc5-b56dc0e7b475

###

POST {{DevHabit.Api_HostAddress}}/habits
Content-Type: application/json
Accept: application/json

{
  "name": "Daily Exercise",
  "description": "Exercise for at least 30 minutes every day",
  "type": "Binary",
  "frequency": {
    "timesPerPeriod": 1,
    "type": "Daily"
  },
  "target": {
    "unit": "minutes",
    "value": 30
  },
  "endDate": null,
  "milestone": null
}

###

POST {{DevHabit.Api_HostAddress}}/habits
Content-Type: application/json
Accept: application/json

{
  "name": "Daily Walk",
  "description": "Walk 4 miles every day",
  "type": 1,
  "frequency": {
    "timesPerPeriod": 1,
    "type": 1
  },
  "target": {
    "unit": "miles",
    "value": 4
  },
  "endDate": null,
  "milestone": null
}

###

GET {{DevHabit.Api_HostAddress}}/habits/h_1234

###

DELETE {{DevHabit.Api_HostAddress}}/habits/h_0199e18a-5a46-7b70-a5f5-ff83eeaa914f

###

PUT {{DevHabit.Api_HostAddress}}/habits/h_0199e18a-5a46-7b70-a5f5-ff83eeaa914f
Content-Type: application/json
Accept: application/json

{
      "description": "Exercise for at least 30 minutes every day",
      "endDate": null,
      "frequency": {
        "timesPerPeriod": 1,
        "type": "Daily"
      },
      "milestone": {
        "current": 20,
        "target": 30
      },
      "name": "Daily Exercise",
      "target": {
        "unit": "minutes",
        "value": 20
      },
      "type": "Binary"
    }

###

PATCH {{DevHabit.Api_HostAddress}}/habits/h_0199e18a-5a46-7b70-a5f5-ff83eeaa914f
Content-Type: application/json
Accept: application/json

[
  {
    "op": "replace",
    "path": "/isarchived",
    "value": false
  }
    
]

###

PUT {{DevHabit.Api_HostAddress}}/habits/h_0199e8ce-4522-7d72-9fc5-b56dc0e7b475/tags
Content-Type: application/json
Accept: application/json

{
  "tagids": [
    "t_0199e8cf-b6e8-7b38-a496-50882f337fa0",
     "t_0199e8cf-c605-7521-ba65-3dd922302649",
     "t_0199e8cf-d1e8-71b7-8cb0-ba29b7fac53b"
  ]
}

###

DELETE {{DevHabit.Api_HostAddress}}/habits/h_0199e8ce-4522-7d72-9fc5-b56dc0e7b475/tags/t_0199e8cf-d1e8-71b7-8cb0-ba29b7fac53b

###
